# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the bond price with discrete annual compounding
#'
#' @param times A vector of cashflow periods.
#' @param cashflows A vector of cashflow amounts.
#' @param rate The single rate at which to discount all cashflows.
#' @export
NULL

#'
#' @param times A vector of cashflow periods.
#' @param cashflows A vector of cashflow amounts.
#' @param price The bond price for which we want to calculate the yield.
#' @export
NULL

bond_price <- function(times, cashflows, rate) {
    .Call(`_FinancialFunctions_bond_price`, times, cashflows, rate)
}

bond_ytm <- function(times, cashflows, price) {
    .Call(`_FinancialFunctions_bond_ytm`, times, cashflows, price)
}

